// export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";

export const GET_CART_ITEMS_REQUEST = "GET_CART_ITEMS_REQUEST";
export const GET_CART_ITEMS_SUCCESS = "GET_CART_ITEMS_SUCCESS";
export const GET_CART_ITEMS_FAIL = "GET_CART_ITEMS_FAIL";

// export const REMOVE_CART_ITEM_REQUEST = "REMOVE_CART_ITEM_REQUEST";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
// export const REMOVE_CART_ITEM_FAIL = "REMOVE_CART_ITEM_FAIL";

// export const UPDATE_CART_ITEM_REQUEST = "UPDATE_CART_ITEM_REQUEST";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
// export const UPDATE_CART_ITEM_FAIL = "UPDATE_CART_ITEM_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
