export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOAD_REQUEST = "USER_LOAD_REQUEST";
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";
export const USER_LOAD_FAIL = "USER_LOAD_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const UPDATE_USER_NAME_REQUEST = "UPDATE_USER_NAME_REQUEST";
export const UPDATE_USER_NAME_SUCCESS = "UPDATE_USER_NAME_SUCCESS";
export const UPDATE_NAME_FAIL = "UPDATE_NAME_FAIL";
export const UPDATE_NAME_RESET = "UPDATE_NAME_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
